.PHONY: clean All

All:
	@echo "----------Building project:[ Rocket_Gen2 - Debug ]----------"
	@cd "Rocket_Gen2" && "$(MAKE)" -f  "Rocket_Gen2.mk"
clean:
	@echo "----------Cleaning project:[ Rocket_Gen2 - Debug ]----------"
	@cd "Rocket_Gen2" && "$(MAKE)" -f  "Rocket_Gen2.mk" clean
